name = "CS5232"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Project"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0"


[[lean_lib]]
name = "Project"
